use crate::dungeon::dungeon::DUNGEON_ORIGIN;
use glam::IVec2;

pub const DOOR_POSITIONS: [IVec2; 60] = [
    IVec2::new(DUNGEON_ORIGIN.x + 31,  DUNGEON_ORIGIN.y + 15),
    IVec2::new(DUNGEON_ORIGIN.x + 63,  DUNGEON_ORIGIN.y + 15),
    IVec2::new(DUNGEON_ORIGIN.x + 95,  DUNGEON_ORIGIN.y + 15),
    IVec2::new(DUNGEON_ORIGIN.x + 127, DUNGEON_ORIGIN.y + 15),
    IVec2::new(DUNGEON_ORIGIN.x + 159, DUNGEON_ORIGIN.y + 15),

    IVec2::new(DUNGEON_ORIGIN.x + 15,  DUNGEON_ORIGIN.y + 31),
    IVec2::new(DUNGEON_ORIGIN.x + 47,  DUNGEON_ORIGIN.y + 31),
    IVec2::new(DUNGEON_ORIGIN.x + 79,  DUNGEON_ORIGIN.y + 31),
    IVec2::new(DUNGEON_ORIGIN.x + 111, DUNGEON_ORIGIN.y + 31),
    IVec2::new(DUNGEON_ORIGIN.x + 143, DUNGEON_ORIGIN.y + 31),
    IVec2::new(DUNGEON_ORIGIN.x + 175, DUNGEON_ORIGIN.y + 31),

    IVec2::new(DUNGEON_ORIGIN.x + 31,  DUNGEON_ORIGIN.y + 47),
    IVec2::new(DUNGEON_ORIGIN.x + 63,  DUNGEON_ORIGIN.y + 47),
    IVec2::new(DUNGEON_ORIGIN.x + 95,  DUNGEON_ORIGIN.y + 47),
    IVec2::new(DUNGEON_ORIGIN.x + 127, DUNGEON_ORIGIN.y + 47),
    IVec2::new(DUNGEON_ORIGIN.x + 159, DUNGEON_ORIGIN.y + 47),

    IVec2::new(DUNGEON_ORIGIN.x + 15,  DUNGEON_ORIGIN.y + 63),
    IVec2::new(DUNGEON_ORIGIN.x + 47,  DUNGEON_ORIGIN.y + 63),
    IVec2::new(DUNGEON_ORIGIN.x + 79,  DUNGEON_ORIGIN.y + 63),
    IVec2::new(DUNGEON_ORIGIN.x + 111, DUNGEON_ORIGIN.y + 63),
    IVec2::new(DUNGEON_ORIGIN.x + 143, DUNGEON_ORIGIN.y + 63),
    IVec2::new(DUNGEON_ORIGIN.x + 175, DUNGEON_ORIGIN.y + 63),

    IVec2::new(DUNGEON_ORIGIN.x + 31,  DUNGEON_ORIGIN.y + 79),
    IVec2::new(DUNGEON_ORIGIN.x + 63,  DUNGEON_ORIGIN.y + 79),
    IVec2::new(DUNGEON_ORIGIN.x + 95,  DUNGEON_ORIGIN.y + 79),
    IVec2::new(DUNGEON_ORIGIN.x + 127, DUNGEON_ORIGIN.y + 79),
    IVec2::new(DUNGEON_ORIGIN.x + 159, DUNGEON_ORIGIN.y + 79),

    IVec2::new(DUNGEON_ORIGIN.x + 15,  DUNGEON_ORIGIN.y + 95),
    IVec2::new(DUNGEON_ORIGIN.x + 47,  DUNGEON_ORIGIN.y + 95),
    IVec2::new(DUNGEON_ORIGIN.x + 79,  DUNGEON_ORIGIN.y + 95),
    IVec2::new(DUNGEON_ORIGIN.x + 111, DUNGEON_ORIGIN.y + 95),
    IVec2::new(DUNGEON_ORIGIN.x + 143, DUNGEON_ORIGIN.y + 95),
    IVec2::new(DUNGEON_ORIGIN.x + 175, DUNGEON_ORIGIN.y + 95),

    IVec2::new(DUNGEON_ORIGIN.x + 31,  DUNGEON_ORIGIN.y + 111),
    IVec2::new(DUNGEON_ORIGIN.x + 63,  DUNGEON_ORIGIN.y + 111),
    IVec2::new(DUNGEON_ORIGIN.x + 95,  DUNGEON_ORIGIN.y + 111),
    IVec2::new(DUNGEON_ORIGIN.x + 127, DUNGEON_ORIGIN.y + 111),
    IVec2::new(DUNGEON_ORIGIN.x + 159, DUNGEON_ORIGIN.y + 111),

    IVec2::new(DUNGEON_ORIGIN.x + 15,  DUNGEON_ORIGIN.y + 127),
    IVec2::new(DUNGEON_ORIGIN.x + 47,  DUNGEON_ORIGIN.y + 127),
    IVec2::new(DUNGEON_ORIGIN.x + 79,  DUNGEON_ORIGIN.y + 127),
    IVec2::new(DUNGEON_ORIGIN.x + 111, DUNGEON_ORIGIN.y + 127),
    IVec2::new(DUNGEON_ORIGIN.x + 143, DUNGEON_ORIGIN.y + 127),
    IVec2::new(DUNGEON_ORIGIN.x + 175, DUNGEON_ORIGIN.y + 127),

    IVec2::new(DUNGEON_ORIGIN.x + 31,  DUNGEON_ORIGIN.y + 143),
    IVec2::new(DUNGEON_ORIGIN.x + 63,  DUNGEON_ORIGIN.y + 143),
    IVec2::new(DUNGEON_ORIGIN.x + 95,  DUNGEON_ORIGIN.y + 143),
    IVec2::new(DUNGEON_ORIGIN.x + 127, DUNGEON_ORIGIN.y + 143),
    IVec2::new(DUNGEON_ORIGIN.x + 159, DUNGEON_ORIGIN.y + 143),

    IVec2::new(DUNGEON_ORIGIN.x + 15,  DUNGEON_ORIGIN.y + 159),
    IVec2::new(DUNGEON_ORIGIN.x + 47,  DUNGEON_ORIGIN.y + 159),
    IVec2::new(DUNGEON_ORIGIN.x + 79,  DUNGEON_ORIGIN.y + 159),
    IVec2::new(DUNGEON_ORIGIN.x + 111, DUNGEON_ORIGIN.y + 159),
    IVec2::new(DUNGEON_ORIGIN.x + 143, DUNGEON_ORIGIN.y + 159),
    IVec2::new(DUNGEON_ORIGIN.x + 175, DUNGEON_ORIGIN.y + 159),

    IVec2::new(DUNGEON_ORIGIN.x + 31,  DUNGEON_ORIGIN.y + 175),
    IVec2::new(DUNGEON_ORIGIN.x + 63,  DUNGEON_ORIGIN.y + 175),
    IVec2::new(DUNGEON_ORIGIN.x + 95,  DUNGEON_ORIGIN.y + 175),
    IVec2::new(DUNGEON_ORIGIN.x + 127, DUNGEON_ORIGIN.y + 175),
    IVec2::new(DUNGEON_ORIGIN.x + 159, DUNGEON_ORIGIN.y + 175),
];